// <auto-generated />
namespace ZooApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tickettriviabooking2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tickettriviabooking2));
        
        string IMigrationMetadata.Id
        {
            get { return "202107081505428_ticket-trivia-booking2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
