// <auto-generated />
namespace ZooApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class keepersanimals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keepersanimals));
        
        string IMigrationMetadata.Id
        {
            get { return "202105070424072_keepers-animals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
